// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using CoffeManagement.Models;
using Microsoft.EntityFrameworkCore;

namespace CoffeManagement.Data;

public partial class DBContext : DbContext
{
    public DBContext(DbContextOptions<DBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Drinks> Drinks { get; set; }

    public virtual DbSet<DrinksSize> DrinksSizes { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Drinks>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Drinks__3214EC07E8A3978D");

            entity.Property(e => e.Image)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Name).HasMaxLength(255);
        });

        modelBuilder.Entity<DrinksSize>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__DrinksSi__3214EC071CEEB5B6");

            entity.Property(e => e.Size)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.Drink).WithMany(p => p.DrinksSizes)
                .HasForeignKey(d => d.DrinkId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DrinksSizes_Drinks");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}