// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoffeManagement.Models;

public partial class DrinksSize
{
    public int Id { get; set; }

    public int DrinkId { get; set; }

    public string Size { get; set; }

    public double Ratio { get; set; }

    public double Price { get; set; }

    public virtual Drinks Drink { get; set; }
}