// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoffeManagement.Models;

public partial class DrinkRating
{
    public int Id { get; set; }

    public int DrinkId { get; set; }

    public int OrderId { get; set; }

    public decimal Rating { get; set; }

    public string Content { get; set; }

    public int? FeedbackStaffId { get; set; }

    public string Feedback { get; set; }

    public DateTime? FeedbackAt { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Drink Drink { get; set; }

    public virtual Staff FeedbackStaff { get; set; }

    public virtual Order Order { get; set; }
}