// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoffeManagement.Models;

public partial class IngredientStock
{
    public int Id { get; set; }

    public int? IngredientId { get; set; }

    public int Amount { get; set; }

    public int Remain { get; set; }

    public double Cost { get; set; }

    public DateTime? ReceivedAt { get; set; }

    public DateTime ExpiredAt { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Ingredient Ingredient { get; set; }
}