// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoffeManagement.Models;

public partial class OrderDetail
{
    public int Id { get; set; }

    public int OrderId { get; set; }

    public int DrinkId { get; set; }

    public int DrinkSizeId { get; set; }

    public int Quantity { get; set; }

    public double Price { get; set; }

    public double IngredientCost { get; set; }

    public string Note { get; set; }

    public virtual Drink Drink { get; set; }

    public virtual DrinkSize DrinkSize { get; set; }

    public virtual Recipe Order { get; set; }
}