// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoffeManagement.Models;

public partial class Order
{
    public int Id { get; set; }

    public string Type { get; set; }

    public int StaffId { get; set; }

    public int BranchId { get; set; }

    public int? CustomerId { get; set; }

    public string ShippingAddress { get; set; }

    public string Status { get; set; }

    public string PaymentMethod { get; set; }

    public string CustomerNote { get; set; }

    public string StaffNote { get; set; }

    public DateTime? OrderdAt { get; set; }

    public double TotalPrice { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Staff Staff { get; set; }
}