// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoffeManagement.Models;

public partial class RecipeDetail
{
    public int Id { get; set; }

    public int RecipeId { get; set; }

    public int IngredientId { get; set; }

    public double Amount { get; set; }

    public virtual Ingredient Ingredient { get; set; }

    public virtual Recipe Recipe { get; set; }
}