// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoffeManagement.Models;

public partial class Staff
{
    public int Id { get; set; }

    public string FullName { get; set; }

    public DateOnly Birthday { get; set; }

    public string Address { get; set; }

    public string Avatar { get; set; }

    public string Cccd { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public double? Salary { get; set; }

    public int? OnJobDays { get; set; }

    public int? AsentDays { get; set; }

    public string Position { get; set; }

    public int BranchId { get; set; }

    public int? AccountId { get; set; }

    public bool? IsDeleted { get; set; }

    public bool? IsActivated { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Account Account { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual ICollection<Order> OrderStaffCanceleds { get; set; } = new List<Order>();

    public virtual ICollection<Order> OrderStaffs { get; set; } = new List<Order>();
}