// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoffeManagement.Models;

public partial class Voucher
{
    public int Id { get; set; }

    public string Staus { get; set; }

    public double Discount { get; set; }

    public int Amount { get; set; }

    public int Remain { get; set; }

    public DateTime ExpiredAt { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<VoucherApply> VoucherApplies { get; set; } = new List<VoucherApply>();
}